version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: e-deals
    restart: "no"
    working_dir: /var/www
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./config/sites-available:/etc/apache2/sites-available
      - ./crontabs:/var/spool/cron/crontabs
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: edeals
    volumes:
      #- ./db-data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "33060:33060"
  db-admin:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
